apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-app
  labels:
    app: details-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: details-app
  template:
    metadata:
      labels:
        app: details-app
  spec:
    containers:
      - name: details-app-container
        image: gcr.io/mavericsy-1732863904219/details:1.0
        ports:
        - containerPort: 8084